README.md: improve `gen.yaml` template
Add whitespace to make the file easier to read. Add some comments.

Comment out `include_domains` and `exclude_domains`, since the default
of including all domains is probably more useful than either for the
average user than either of the examples.

Make the example `include_domains` look more like what would be needed
to get the `example` app working, including generating the `zone`
domain.

And leave `ha_auth_token` blank rather than setting it to
"your_auth_token". The reason is that this gives better results in two
scenarios that might plausibly be hit by a beginner:

1.  User tries to run `generate` without setting the authorization
    token either in this file or in the environment.

    Before this change: a confusing error message, based on trying to
    use "your_auth_token" as the token:

        Generating entities.go...
        2025/10/12 09:58:05 ERROR Auth token is invalid. Please double check it or create a new token in your Home Assistant profile
        Error generating entities: failed to create app: invalid authentication token
        exit status 1

    After this change: a more helpful error message:

        Generating entities.go...
        Error: url and ha_auth_token are required in config
        exit status 1

2.  User sets `HA_AUTH_TOKEN` but forgets to clear this entry.

    Before this change: a confusing error message, based on using
    "your_auth_token" rather than `$HA_AUTH_TOKEN` as the token:

        Generating entities.go...
        2025/10/12 10:04:15 ERROR Auth token is invalid. Please double check it or create a new token in your Home Assistant profile
        Error generating entities: failed to create app: invalid authentication token
        exit status 1

    After this change: Success!